#! /bin/sh

# Use pointer cursor instead of `x` cursor
xsetroot -cursor_name left_ptr &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         4
bspc config window_gap          12

bspc config focused_border_color "#86c1b9"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp state=floating follow=on
bspc rule -a Thunar state=floating follow=on
bspc rule -a Emacs state=tiled follow=on

$HOME/.config/polybar/launch.sh
